[package]
name = "adventofcode-2018"
version = "0.1.0"
authors = ["Thomas McNiven <hello@vevix.net>"]
edition = "2018"

[dependencies]
aoc-runner = "0.2.0"
aoc-runner-derive = "0.2.0"
regex = "1"
hashbrown = "0.1"
linked-list = "0.0.3"
