[package]
name = "adventofcode-2018"
version = "0.1.0"
authors = ["Thomas McNiven <hello@vevix.net>"]
edition = "2018"

[dependencies]
aoc-runner = "0.2.2"
aoc-runner-derive = "0.2.2"
regex = "1"
hashbrown = "0.1"
pathfinding = "1.1"
